apiVersion: filecoin.kotal.io/v1alpha1
kind: Node
metadata:
  name: my-node
spec:
  network: mainnet
  api: true
  apiPort: 1234
  apiRequestTimeout: 30
  disableMetadataLog: false
  logging: debug
  p2pPort: 4444
  ipfsPeerEndpoint: /dns4/peer-sample/tcp/5001
  ipfsOnlineMode: false
  resources:
    cpu: "1"
    memory: "1Gi"
