// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconNode) DeepCopyInto(out *BeaconNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconNode.
func (in *BeaconNode) DeepCopy() *BeaconNode {
	if in == nil {
		return nil
	}
	out := new(BeaconNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeaconNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconNodeList) DeepCopyInto(out *BeaconNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BeaconNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconNodeList.
func (in *BeaconNodeList) DeepCopy() *BeaconNodeList {
	if in == nil {
		return nil
	}
	out := new(BeaconNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeaconNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconNodeSpec) DeepCopyInto(out *BeaconNodeSpec) {
	*out = *in
	if in.Eth1Endpoints != nil {
		in, out := &in.Eth1Endpoints, &out.Eth1Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconNodeSpec.
func (in *BeaconNodeSpec) DeepCopy() *BeaconNodeSpec {
	if in == nil {
		return nil
	}
	out := new(BeaconNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconNodeStatus) DeepCopyInto(out *BeaconNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconNodeStatus.
func (in *BeaconNodeStatus) DeepCopy() *BeaconNodeStatus {
	if in == nil {
		return nil
	}
	out := new(BeaconNodeStatus)
	in.DeepCopyInto(out)
	return out
}
