# permissions for end users to edit nodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-editor-role
rules:
  - apiGroups:
      - bitcoin.kotal.io
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bitcoin.kotal.io
    resources:
      - nodes/status
    verbs:
      - get
