# permissions for end users to view nodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-viewer-role
rules:
  - apiGroups:
      - chainlink.kotal.io
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - chainlink.kotal.io
    resources:
      - nodes/status
    verbs:
      - get
