# permissions for end users to view clusterpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpeer-viewer-role
rules:
  - apiGroups:
      - ipfs.kotal.io
    resources:
      - clusterpeers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ipfs.kotal.io
    resources:
      - clusterpeers/status
    verbs:
      - get
