# permissions for end users to edit validators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: validator-editor-role
rules:
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - validators
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - validators/status
    verbs:
      - get
