# permissions for end users to view validators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: validator-viewer-role
rules:
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - validators
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - validators/status
    verbs:
      - get
