# permissions for end users to view beaconnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beaconnode-viewer-role
rules:
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - beaconnodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - beaconnodes/status
    verbs:
      - get
