# permissions for end users to edit beaconnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beaconnode-editor-role
rules:
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - beaconnodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - beaconnodes/status
    verbs:
      - get
