apiVersion: ethereum2.kotal.io/v1alpha1
kind: Validator
metadata:
  name: lighthouse-validator
spec:
  client: lighthouse
  network: goerli
  logging: info
  beaconEndpoints:
    - http://lighthouse-beacon-node:8888
  graffiti: Validated by Kotal
  keystores:
    - secretName: my-validator
      publicKey: "0x83dbb18e088cb16a07fca598db2ac24da3e8549601eedd75eb28d8a9d4be405f49f7dbdcad5c9d7df54a8a40a143e852"
  feeRecipient: "0xd8da6bf26964af9d7eed9e03e53415d37aa96045"
  resources:
    # these resources are only for testing
    # change resources depending on your use case
    cpu: "1"
    memory: "1Gi"
