apiVersion: ethereum2.kotal.io/v1alpha1
kind: Validator
metadata:
  name: prysm-validator
spec:
  client: prysm
  network: mainnet
  logging: info
  beaconEndpoints:
    # it gives too many colons error when protocol (https://) is added
    - prysm-beacon-node:8888
  graffiti: Validated by Kotal
  certSecretName: "beaconnode-cert"
  walletPasswordSecret: wallet-password
  keystores:
    - secretName: my-validator
  feeRecipient: "0xd8da6bf26964af9d7eed9e03e53415d37aa96045"
  resources:
    # these resources are only for testing
    # change resources depending on your use case
    cpu: "1"
    memory: "1Gi"
