# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: goerli-geth-nodekey
stringData:
  key: 5df5eff7ef9e4e82739b68a34c6b23608d79ee8daf3b598a01ffb0dd7aa3a2fd
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
stringData:
  secret: fbe0c28a10274b27babf3c51e88a7435318e25fad4de877e5a63a67d0d65fdbb
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: goerli-geth-node
spec:
  network: goerli
  client: geth
  nodePrivateKeySecretName: goerli-geth-nodekey
  rpc: true
  engine: true
  jwtSecretName: jwt-secret
  rpcPort: 8599
  corsDomains:
    - example.kotal.io
  rpcAPI:
    - web3
    - net
    - eth
  graphql: true
  graphqlPort: 8777
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
