# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: goerli-nethermind-nodekey
stringData:
  key: 608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
stringData:
  secret: fbe0c28a10274b27babf3c51e88a7435318e25fad4de877e5a63a67d0d65fdbb
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: goerli-nethermind-node
spec:
  network: goerli
  client: nethermind
  nodePrivateKeySecretName: goerli-nethermind-nodekey
  logging: info
  engine: true
  jwtSecretName: jwt-secret
  rpc: true
  rpcPort: 9999
  rpcAPI:
    - eth
    - admin
  p2pPort: 30304
  ws: true
  wsPort: 8888
  syncMode: fast
  staticNodes:
    - "enode://2281549869465d98e90cebc45e1d6834a01465a990add7bcf07a49287e7e66b50ca27f9c70a46190cef7ad746dd5d5b6b9dfee0c9954104c8e9bd0d42758ec58@10.5.0.2:30300"
  resources:
    cpu: "1"
    memory: "1Gi"
