# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/aptos.kotal.io_nodes.yaml
  - bases/bitcoin.kotal.io_nodes.yaml
  - bases/chainlink.kotal.io_nodes.yaml
  - bases/ethereum.kotal.io_nodes.yaml
  - bases/ethereum2.kotal.io_beaconnodes.yaml
  - bases/ethereum2.kotal.io_validators.yaml
  - bases/filecoin.kotal.io_nodes.yaml
  - bases/graph.kotal.io_nodes.yaml
  - bases/ipfs.kotal.io_peers.yaml
  - bases/ipfs.kotal.io_clusterpeers.yaml
  - bases/near.kotal.io_nodes.yaml
  - bases/polkadot.kotal.io_nodes.yaml
  - bases/stacks.kotal.io_nodes.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
  # patches here are for enabling the conversion webhook for each CRD
  # - patches/webhook_in_aptos_nodes.yaml
  # - patches/webhook_in_bitcoin_nodes.yaml
  # - patches/webhook_in_chainlink_nodes.yaml
  # - patches/webhook_in_ethereum_nodes.yaml
  # - patches/webhook_in_ethereum2_beaconnodes.yaml
  # - patches/webhook_in_ethereum2_validators.yaml
  # - patches/webhook_in_filecoin_nodes.yaml
  # - patches/webhook_in_graph_nodes.yaml
  # - patches/webhook_in_ipfs_peers.yaml
  # - patches/webhook_in_ipfs_clusterpeers.yaml
  # - patches/webhook_in_near_nodes.yaml
  # - patches/webhook_in_polkadot_nodes.yaml
  # - patches/webhook_in_stacks_nodes.yaml
  # +kubebuilder:scaffold:crdkustomizewebhookpatch
  # [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
  # patches here are for enabling the CA injection for each CRD
  - patches/cainjection_in_aptos_nodes.yaml
  - patches/cainjection_in_bitcoin_nodes.yaml
  - patches/cainjection_in_chainlink_nodes.yaml
  - patches/cainjection_in_ethereum_nodes.yaml
  - patches/cainjection_in_ethereum2_beaconnodes.yaml
  - patches/cainjection_in_ethereum2_validators.yaml
  - patches/cainjection_in_filecoin_nodes.yaml
  - patches/cainjection_in_graph_nodes.yaml
  - patches/cainjection_in_ipfs_peers.yaml
  - patches/cainjection_in_ipfs_clusterpeers.yaml
  - patches/cainjection_in_near_nodes.yaml
  - patches/cainjection_in_polkadot_nodes.yaml
  - patches/cainjection_in_stacks_nodes.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
